-- 004_pgvector.sql
-- Activates the pgvector extension for Phase 2 RAG pipeline.
-- The vector(1536) embedding columns on tender_document_chunks, boq_items,
-- and rate_catalog were declared in 001_core_schema.sql and are already live.
-- They remain NULL until the Phase 2 RAG pipeline populates them.

CREATE EXTENSION IF NOT EXISTS vector;

-- Phase 2: embeddings are generated by the Claude API (text-embedding-3-small,
-- 1536 dimensions) and stored here to enable semantic search over tender
-- documents and BOQ / rate-catalog items.
COMMENT ON COLUMN tender_document_chunks.embedding IS
  'OpenAI text-embedding-3-small vector (1536-d). Populated in Phase 2 RAG pipeline. NULL until then.';

COMMENT ON COLUMN boq_items.embedding IS
  'OpenAI text-embedding-3-small vector (1536-d). Populated in Phase 2 RAG pipeline. NULL until then.';

COMMENT ON COLUMN rate_catalog.embedding IS
  'OpenAI text-embedding-3-small vector (1536-d). Populated in Phase 2 RAG pipeline. NULL until then.';
